### ISSUE TITLE
Aolab

### ISSUE THREAD

**Issue by 1995parham** [I1820/I1820.github.io#5]
@pesehr I want to provide a description of our lab and our team on this website. Do you agree? I think it would be good if there is a clear relationship between this product and Aolab.

**Comment by pesehr** [comment]
I think it's better to find a unified template for the websites of our
products. We don't need to have "about" and "team" sections on all the
sites.  Just mention that this product powered by AoLab and provide a link
to AoLab.org.

**Comment by 1995parham** [comment]
@pesehr That's great Sepehr! I will remove these sections.
